platform :ios, '7.0'
pod 'UMengAnalytics-NO-IDFA', '~> 4.0.3'
pod 'NJKWebViewProgress'

platform :ios, '8.0'
use_frameworks!
pod 'FMDB', '~> 2.6.2'
pod 'Alamofire', '~> 3.0'
pod 'GSMessages'
pod 'BRYXBanner'
pod 'Timepiece'
pod 'Fabric'
pod 'Crashlytics'
pod 'TextFieldEffects'
pod 'Charts', '~> 2.2.4'
pod 'AutocompleteField','~> 1.1'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'MRProgress'
pod 'UIColor_Hex_Swift'
# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
