platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'FMDB'
pod 'UMengAnalytics-NO-IDFA'

#pod 'Charts' 

# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
