platform :ios, '7.0'
pod 'FMDB', '~> 2.6'
pod 'UMengAnalytics-NO-IDFA'
pod 'NJKWebViewProgress'

platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0'
pod 'GSMessages'
#pod 'Charts' 

# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
